### ISSUE TITLE
You are neat!!!

### ISSUE THREAD

**Issue by TheRealOne78** [alcaparra/bruh_momentos#3]
There was not email or smth in order to contact you.
I just want to say that YOU ARE SO FUNNY AND NEAT!!!
I like your jokes, I saw your comments in some nvidia issues(funny af), and also the Porting NVIDIA to HolyC, damn that was a good one, so good that you are also featured in mentaloutlaw's video about nvidia at 5:34 https://youtu.be/7MjtsiATEGQ 
You are very funny and cool!!! :)))) Keep it up like this and have a nice day

**Comment by alcaparra** [comment]
lmao, nice!
